apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eip.fullname" . }}-config
  namespace: {{ include "eip.namespace" . }}
  labels:
    {{- include "eip.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  Logging__LogLevel__Default: {{ .Values.config.logLevel | quote }}
  Infrastructure__Temporal__Host: {{ .Values.infrastructure.temporal.host | quote }}
  Infrastructure__Temporal__Port: {{ .Values.infrastructure.temporal.port | quote }}
  Infrastructure__Cassandra__Host: {{ .Values.infrastructure.cassandra.host | quote }}
  Infrastructure__Cassandra__Port: {{ .Values.infrastructure.cassandra.port | quote }}
  Infrastructure__Nats__Host: {{ .Values.infrastructure.nats.host | quote }}
  Infrastructure__Nats__Port: {{ .Values.infrastructure.nats.port | quote }}
  Infrastructure__Kafka__BootstrapServers: {{ .Values.infrastructure.kafka.bootstrapServers | quote }}
  Infrastructure__Ollama__Host: {{ .Values.infrastructure.ollama.host | quote }}
  Infrastructure__Ollama__Port: {{ .Values.infrastructure.ollama.port | quote }}
  Infrastructure__RagFlow__Host: {{ .Values.infrastructure.ragflow.host | quote }}
  Infrastructure__RagFlow__ApiPort: {{ .Values.infrastructure.ragflow.apiPort | quote }}
  Infrastructure__Loki__Host: {{ .Values.infrastructure.loki.host | quote }}
  Infrastructure__Loki__Port: {{ .Values.infrastructure.loki.port | quote }}
