using FluentAssertions;
using Xunit;

using EnterpriseIntegrationPlatform.Contracts;

namespace EnterpriseIntegrationPlatform.Tests.PatternDemo;

/// <summary>
/// Demonstrates the Correlation Identifier pattern.
/// Matches related messages across services using a shared correlation ID.
/// BizTalk equivalent: Promoted CorrelationId property, correlation sets.
/// EIP: Correlation Identifier (p. 163)
/// </summary>
public class CorrelationIdentifierTests
{
    private record OrderRequest(string ProductId, int Quantity);
    private record OrderConfirmation(string OrderId, string Status);
    private record ShipmentNotification(string OrderId, string TrackingNumber);

    [Fact]
    public void RelatedMessages_ShareCorrelationId()
    {
        var correlationId = Guid.NewGuid();

        // Step 1: Order request
        var request = IntegrationEnvelope<OrderRequest>.Create(
            new OrderRequest("WIDGET-42", 10),
            "Storefront", "OrderRequest",
            correlationId);

        // Step 2: Order confirmation (same correlation ID)
        var confirmation = IntegrationEnvelope<OrderConfirmation>.Create(
            new OrderConfirmation("ORD-001", "Confirmed"),
            "OrderService", "OrderConfirmation",
            correlationId,
            causationId: request.MessageId);

        // Step 3: Shipment notification (same correlation ID)
        var shipment = IntegrationEnvelope<ShipmentNotification>.Create(
            new ShipmentNotification("ORD-001", "TRK-456"),
            "Warehouse", "ShipmentNotification",
            correlationId,
            causationId: confirmation.MessageId);

        // All three messages share the same correlation ID
        request.CorrelationId.Should().Be(correlationId);
        confirmation.CorrelationId.Should().Be(correlationId);
        shipment.CorrelationId.Should().Be(correlationId);

        // Causation chain: request → confirmation → shipment
        confirmation.CausationId.Should().Be(request.MessageId);
        shipment.CausationId.Should().Be(confirmation.MessageId);
    }

    [Fact]
    public void AutoGeneratedCorrelationId_WhenNotProvided()
    {
        var envelope = IntegrationEnvelope<OrderRequest>.Create(
            new OrderRequest("PROD-01", 1), "API", "OrderRequest");

        envelope.CorrelationId.Should().NotBeEmpty();
    }
}
