// ============================================================================
// Tutorial 01 – Introduction (Lab)
// ============================================================================
// EIP Pattern: Canonical Data Model
// End-to-End: Create envelopes, publish through MockEndpoint, verify
// canonical fields preserved at output.
// ============================================================================

using NUnit.Framework;
using TutorialLabs.Infrastructure;
using EnterpriseIntegrationPlatform.Contracts;

namespace TutorialLabs.Tutorial01;

[TestFixture]
public sealed class Lab
{
    private MockEndpoint _output = null!;

    [SetUp]
    public void SetUp()
    {
        _output = new MockEndpoint("output");
    }

    [TearDown]
    public async Task TearDown()
    {
        await _output.DisposeAsync();
    }

    [Test]
    public async Task EndToEnd_StringPayload_CanonicalFieldsPreserved()
    {
        var envelope = IntegrationEnvelope<string>.Create(
            "Hello, EIP!", "Tutorial01", "greeting.created");

        await _output.PublishAsync(envelope, "greetings");

        _output.AssertReceivedCount(1);
        var received = _output.GetReceived<string>();
        Assert.That(received.Payload, Is.EqualTo("Hello, EIP!"));
        Assert.That(received.Source, Is.EqualTo("Tutorial01"));
        Assert.That(received.MessageType, Is.EqualTo("greeting.created"));
    }

    [Test]
    public async Task EndToEnd_AutoGeneratedIds_PreservedThroughPipeline()
    {
        var envelope = IntegrationEnvelope<string>.Create(
            "payload", "source", "type");

        await _output.PublishAsync(envelope, "ids-topic");

        var received = _output.GetReceived<string>();
        Assert.That(received.MessageId, Is.EqualTo(envelope.MessageId));
        Assert.That(received.CorrelationId, Is.EqualTo(envelope.CorrelationId));
        Assert.That(received.Timestamp, Is.EqualTo(envelope.Timestamp));
    }

    [Test]
    public async Task EndToEnd_DefaultCanonicalValues_PreservedAtOutput()
    {
        var envelope = IntegrationEnvelope<string>.Create(
            "payload", "source", "type");

        await _output.PublishAsync(envelope, "defaults-topic");

        var received = _output.GetReceived<string>();
        Assert.That(received.SchemaVersion, Is.EqualTo("1.0"));
        Assert.That(received.Priority, Is.EqualTo(MessagePriority.Normal));
        Assert.That(received.Metadata, Is.Empty);
        Assert.That(received.CausationId, Is.Null);
    }

    [Test]
    public async Task EndToEnd_CommandIntent_PreservedAtOutput()
    {
        var envelope = IntegrationEnvelope<string>.Create(
            "PlaceOrder", "OrderService", "order.place") with
        {
            Intent = MessageIntent.Command,
        };

        await _output.PublishAsync(envelope, "commands");

        var received = _output.GetReceived<string>();
        Assert.That(received.Intent, Is.EqualTo(MessageIntent.Command));
        Assert.That(received.Payload, Is.EqualTo("PlaceOrder"));
    }

    [Test]
    public async Task EndToEnd_DocumentIntent_PreservedAtOutput()
    {
        var envelope = IntegrationEnvelope<string>.Create(
            "{\"sku\":\"ABC\"}", "CatalogService", "product.catalog") with
        {
            Intent = MessageIntent.Document,
        };

        await _output.PublishAsync(envelope, "documents");

        var received = _output.GetReceived<string>();
        Assert.That(received.Intent, Is.EqualTo(MessageIntent.Document));
        Assert.That(received.Payload, Is.EqualTo("{\"sku\":\"ABC\"}"));
    }

    [Test]
    public async Task EndToEnd_EventIntent_PreservedAtOutput()
    {
        var envelope = IntegrationEnvelope<string>.Create(
            "OrderPlaced", "OrderService", "order.placed") with
        {
            Intent = MessageIntent.Event,
        };

        await _output.PublishAsync(envelope, "events");

        var received = _output.GetReceived<string>();
        Assert.That(received.Intent, Is.EqualTo(MessageIntent.Event));
        Assert.That(received.MessageId, Is.EqualTo(envelope.MessageId));
    }
}
