apiVersion: v1
kind: Service
metadata:
  name: admin-api
  namespace: eip
  labels:
    app.kubernetes.io/name: admin-api
    app.kubernetes.io/instance: eip
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: eip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: admin-api
    app.kubernetes.io/instance: eip
