apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eip

resources:
  - namespace.yaml
  - openclaw-web/deployment.yaml
  - openclaw-web/service.yaml
  - admin-api/deployment.yaml
  - admin-api/service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: eip
    includeSelectors: false
