namespace AdminWeb;

/// <summary>
/// Marker class used by <see cref="Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory{TEntryPoint}"/>
/// to locate the Admin.Web assembly entry point for integration testing.
/// This is required because the top-level <c>Program</c> class generated by
/// the .NET SDK cannot be used as a type argument when multiple web projects
/// define the same implicit <c>Program</c> class.
/// </summary>
public sealed class AdminWebMarker;
